export const ios =  {
    "0": "San Francisco",
    "1": "Academy Engraved LET",
    "2": "AcademyEngravedLetPlain",
    "3": "Al Nile",
    "4": "AlNile-Bold",
    "5": "American Typewriter",
    "6": "AmericanTypewriter-Bold",
    "7": "AmericanTypewriter-Condensed",
    "8": "AmericanTypewriter-CondensedBold",
    "9": "AmericanTypewriter-CondensedLight",
    "10": "AmericanTypewriter-Light",
    "11": "AppleColorEmoji",
    "12": "Apple SD Gothic Neo",
    "13": "AppleSDGothicNeo-Bold",
    "14": "AppleSDGothicNeo-Light",
    "15": "AppleSDGothicNeo-Medium",
    "16": "AppleSDGothicNeo-Regular",
    "17": "AppleSDGothicNeo-SemiBold",
    "18": "AppleSDGothicNeo-Thin",
    "19": "AppleSDGothicNeo-UltraLight",
    "20": "Arial",
    "21": "ArialHebrew",
    "22": "ArialRoundedMTBold",
    "23": "Arial-BoldItalicMT",
    "24": "Arial-BoldMT",
    "25": "Arial-ItalicMT",
    "26": "ArialHebrew-Bold",
    "27": "ArialHebrew-Light",
    "28": "ArialMT",
    "29": "Avenir",
    "30": "Avenir Next",
    "31": "Avenir Next Condensed",
    "32": "Avenir-Black",
    "33": "Avenir-BlackOblique",
    "34": "Avenir-Book",
    "35": "Avenir-BookOblique",
    "36": "Avenir-Heavy",
    "37": "Avenir-HeavyOblique",
    "38": "Avenir-Light",
    "39": "Avenir-LightOblique",
    "40": "Avenir-Medium",
    "41": "Avenir-MediumOblique",
    "42": "Avenir-Oblique",
    "43": "Avenir-Roman",
    "44": "AvenirNext-Bold",
    "45": "AvenirNext-BoldItalic",
    "46": "AvenirNext-DemiBold",
    "47": "AvenirNext-DemiBoldItalic",
    "48": "AvenirNext-Heavy",
    "49": "AvenirNext-HeavyItalic",
    "50": "AvenirNext-Italic",
    "51": "AvenirNext-Medium",
    "52": "AvenirNext-MediumItalic",
    "53": "AvenirNext-Regular",
    "54": "AvenirNext-UltraLight",
    "55": "AvenirNext-UltraLightItalic",
    "56": "AvenirNextCondensed-Bold",
    "57": "AvenirNextCondensed-BoldItalic",
    "58": "AvenirNextCondensed-DemiBold",
    "59": "AvenirNextCondensed-DemiBoldItalic",
    "60": "AvenirNextCondensed-Heavy",
    "61": "AvenirNextCondensed-HeavyItalic",
    "62": "AvenirNextCondensed-Italic",
    "63": "AvenirNextCondensed-Medium",
    "64": "AvenirNextCondensed-MediumItalic",
    "65": "AvenirNextCondensed-Regular",
    "66": "AvenirNextCondensed-UltraLight",
    "67": "AvenirNextCondensed-UltraLightItalic",
    "68": "Bangla Sangam MN",
    "69": "Baskerville",
    "70": "Baskerville-Bold",
    "71": "Baskerville-BoldItalic",
    "72": "Baskerville-Italic",
    "73": "Baskerville-SemiBold",
    "74": "Baskerville-SemiBoldItalic",
    "75": "Bodoni 72",
    "76": "Bodoni 72 Oldstyle",
    "77": "Bodoni 72 Smallcaps",
    "78": "Bodoni Ornaments",
    "79": "BodoniOrnamentsITCTT",
    "80": "BodoniSvtyTwoITCTT-Bold",
    "81": "BodoniSvtyTwoITCTT-Book",
    "82": "BodoniSvtyTwoITCTT-BookIt",
    "83": "BodoniSvtyTwoOSITCTT-Bol",
    "84": "BodoniSvtyTwoOSITCTT-Boo",
    "85": "BodoniSvtyTwoSCITCTT-Boo",
    "86": "Bradley Han",
    "87": "BradleyHandITCTT-Bol",
    "88": "Chalkboard S",
    "89": "ChalkboardSE-Bold",
    "90": "ChalkboardSE-Light",
    "91": "ChalkboardSE-Regular",
    "92": "Chalkduster",
    "93": "Cochin",
    "94": "Cochin-Bold",
    "95": "Cochin-BoldItalic",
    "96": "Cochin-Italic",
    "97": "Copperplate",
    "98": "Copperplate-Bold",
    "99": "Copperplate-Light",
    "100": "Courier",
    "101": "Courier New",
    "102": "Courier-Bold",
    "103": "Courier-BoldOblique",
    "104": "Courier-Oblique",
    "105": "CourierNewPS-BoldItalicMT",
    "106": "CourierNewPS-BoldMT",
    "107": "CourierNewPS-ItalicMT",
    "108": "CourierNewPSMT",
    "109": "Damascus",
    "110": "DamascusBold",
    "111": "DamascusLight",
    "112": "DamascusMedium",
    "113": "DamascusSemiBold",
    "114": "DevanagariSangamMN",
    "115": "DevanagariSangamMN-Bold",
    "116": "Didot",
    "117": "Didot-Bold",
    "118": "Didot-Italic",
    "119": "DiwanMishafi",
    "120": "Euphemia UCAS",
    "121": "EuphemiaUCAS-Bold",
    "122": "EuphemiaUCAS-Italic",
    "123": "Farah",
    "124": "Futura",
    "125": "Futura-CondensedExtraBold",
    "126": "Futura-CondensedMedium",
    "127": "Futura-Medium",
    "128": "Futura-MediumItalic",
    "129": "Geeza Pro",
    "130": "GeezaPro-Bold",
    "131": "Georgia",
    "132": "Georgia-Bold",
    "133": "Georgia-BoldItalic",
    "134": "Georgia-Italic",
    "135": "Gill Sans",
    "136": "GillSans-Bold",
    "137": "GillSans-BoldItalic",
    "138": "GillSans-Italic",
    "139": "GillSans-Light",
    "140": "GillSans-LightItalic",
    "141": "GillSans-SemiBold",
    "142": "GillSans-SemiBoldItalic",
    "143": "GillSans-UltraBold",
    "144": "GujaratiSangamMN",
    "145": "GujaratiSangamMN-Bold",
    "146": "Gurmukhi MN",
    "147": "GurmukhiMN-Bold",
    "148": "Heiti SC",
    "149": "Heiti TC",
    "150": "Helvetica",
    "151": "Helvetica Neue",
    "152": "Helvetica-Bold",
    "153": "Helvetica-BoldOblique",
    "154": "Helvetica-Light",
    "155": "Helvetica-LightOblique",
    "156": "Helvetica-Oblique",
    "157": "",
    "158": "HelveticaNeue-BoldItalic",
    "159": "HelveticaNeue-CondensedBlack",
    "160": "HelveticaNeue-CondensedBold",
    "161": "HelveticaNeue-Italic",
    "162": "HelveticaNeue-Light",
    "163": "HelveticaNeue-LightItalic",
    "164": "HelveticaNeue-Medium",
    "165": "HelveticaNeue-MediumItalic",
    "166": "HelveticaNeue-Thin",
    "167": "HelveticaNeue-ThinItalic",
    "168": "HelveticaNeue-UltraLight",
    "169": "HelveticaNeue-UltraLightItalic",
    "170": "Hiragino Mincho ProN",
    "171": "Hiragino Sans",
    "172": "HiraginoSans-W3",
    "173": "HiraginoSans-W6",
    "174": "HiraMinProN-W3",
    "175": "HiraMinProN-W6",
    "176": "Hoefler Text",
    "177": "HoeflerText-Black",
    "178": "HoeflerText-BlackItalic",
    "179": "HoeflerText-Italic",
    "180": "HoeflerText-Regular",
    "181": "Iowan Old Style",
    "182": "IowanOldStyle-Bold",
    "183": "IowanOldStyle-BoldItalic",
    "184": "IowanOldStyle-Italic",
    "185": "IowanOldStyle-Roman",
    "186": "Kailasa",
    "187": "Kailasa-Bold",
    "188": "KannadaSangamMN",
    "189": "KannadaSangamMN-Bold",
    "190": "Khmer Sangam MN",
    "191": "Kohinoor Bangla",
    "192": "Kohinoor Devanagari",
    "193": "Kohinoor Telugu",
    "194": "KohinoorBangla-Light",
    "195": "KohinoorBangla-Regular",
    "196": "KohinoorBangla-Semibold",
    "197": "KohinoorDevanagari-Light",
    "198": "KohinoorDevanagari-Regular",
    "199": "KohinoorDevanagari-Semibold",
    "200": "KohinoorTelugu-Light",
    "201": "KohinoorTelugu-Medium",
    "202": "KohinoorTelugu-Regular",
    "203": "Lao Sangam MN",
    "204": "MalayalamSangamMN",
    "205": "MalayalamSangamMN-Bold",
    "206": "Marker Felt",
    "207": "MarkerFelt-Thin",
    "208": "MarkerFelt-Wide",
    "209": "Menlo",
    "210": "Menlo-Bold",
    "211": "Menlo-BoldItalic",
    "212": "Menlo-Italic",
    "213": "Menlo-Regular",
    "214": "Mishafi",
    "215": "Noteworthy",
    "216": "Noteworthy-Bold",
    "217": "Noteworthy-Light",
    "218": "Optima",
    "219": "Optima-Bold",
    "220": "Optima-BoldItalic",
    "221": "Optima-ExtraBlack",
    "222": "Optima-Italic",
    "223": "Optima-Regular",
    "224": "OriyaSangamMN",
    "225": "OriyaSangamMN-Bold",
    "226": "Palatino",
    "227": "Palatino-Bold",
    "228": "Palatino-BoldItalic",
    "229": "Palatino-Italic",
    "230": "Palatino-Roman",
    "231": "Papyrus",
    "232": "Papyrus-Condensed",
    "233": "Party LET",
    "234": "PartyLetPlain",
    "235": "PingFang HK",
    "236": "PingFang SC",
    "237": "PingFang TC",
    "238": "PingFangHK-Light",
    "239": "PingFangHK-Medium",
    "240": "PingFangHK-Regular",
    "241": "PingFangHK-Semibold",
    "242": "PingFangHK-Thin",
    "243": "PingFangHK-Ultralight",
    "244": "PingFangSC-Light",
    "245": "PingFangSC-Medium",
    "246": "PingFangSC-Regular",
    "247": "PingFangSC-Semibold",
    "248": "PingFangSC-Thin",
    "249": "PingFangSC-Ultralight",
    "250": "PingFangTC-Light",
    "251": "PingFangTC-Medium",
    "252": "PingFangTC-Regular",
    "253": "PingFangTC-Semibold",
    "254": "PingFangTC-Thin",
    "255": "PingFangTC-Ultralight",
    "256": "Savoye LET",
    "257": "SavoyeLetPlain",
    "258": "SinhalaSangamMN",
    "259": "SinhalaSangamMN-Bold",
    "260": "Snell Roundhand",
    "261": "SnellRoundhand-Black",
    "262": "SnellRoundhand-Bold",
    "263": "Symbol",
    "264": "Tamil Sangam MN",
    "265": "TamilSangamMN-Bold",
    "266": "Telugu Sangam MN",
    "267": "Thonburi",
    "268": "Thonburi-Bold",
    "269": "Thonburi-Light",
    "270": "Times New Roman",
    "271": "TimesNewRomanPS-BoldItalicMT",
    "272": "TimesNewRomanPS-BoldMT",
    "273": "TimesNewRomanPS-ItalicMT",
    "274": "TimesNewRomanPSMT",
    "275": "Trebuchet MS",
    "276": "Trebuchet-BoldItalic",
    "277": "TrebuchetMS-Bold",
    "278": "TrebuchetMS-Italic",
    "279": "Verdana",
    "280": "Verdana-Bold",
    "281": "Verdana-BoldItalic",
    "282": "Verdana-Italic",
    "283": "Zapf Dingbats",
    "284": "ZapfDingbatsITC",
    "285": "Zapfino"
}

export const android ={
    "0": "normal",
    "1": "notoserif",
    "2": "sans-serif",
    "3": "sans-serif-light",
    "4": " sans-serif-thin",
    "5": "sans-serif-condensed",
    "6": "sans-serif-medium",
    "7": "serif",
    "8": "Roboto",
    "9": "monospace"
}